### ISSUE TITLE
Not updated regularly enough

### ISSUE THREAD

**Issue by garethtalty** [cjwfuller/cjwfuller.github.io#2]

**Comment by cjwfuller** [comment]
Dear major fan Gareth Talty,

Subscribe to the blog to get the latest posts delivered straight to your inbox!

**Comment by Lokithor** [comment]
Sounds like marketing spam to me.

**Comment by garethtalty** [comment]
This is still an issue

**Comment by cjwfuller** [comment]
Dear Gareth,

Thank you for your message.  To cope with the increasing heavy traffic that this blog experiences, the site's infrastructure is undergoing a revamp to handle the (huge) load.

Thank you for your patience.
